FROM mcr.microsoft.com/dotnet/sdk:8.0 as build
WORKDIR /app
EXPOSE 80
COPY src/Gateways/TesodevOrderApp.Gateway/*.csproj src/Gateways/TesodevOrderApp.Gateway/
RUN dotnet restore src/Gateways/TesodevOrderApp.Gateway/*.csproj
COPY . .
RUN dotnet publish src/Gateways/TesodevOrderApp.Gateway/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:8.0 as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet", "TesodevOrderApp.Gateway.dll" ]